import React, { useState } from "react";
import Head from "next/head";
import { Wrapper } from "@/components/styles/general";
import styled from "styled-components";
import { colors } from "@/constants/colors";
import { sampleData } from "@/constants/sampleData";
import { DragDropContext, Draggable, Droppable } from "@hello-pangea/dnd";
import TaskBoardParent from "@/components/compound/taskboard/TaskBoardParent";
import { useRouter } from "next/router";
import { useGetTaskboard } from "@/hooks/taskboard/taskboard.hook";

export default function Home() {
  const [stores, setStores] = useState(sampleData);
  const router = useRouter();
  const { id } = router?.query;

  return (
    <>
      <Head>
        <title>Tasky Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TaskBoardParent data={taskboard} />
    </>
  );
}

export async function getStaticProps(context) {
  console.log({ context });
  return {
    props: {
      foo: false,
    },
  };
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true,
  };
}
